# Permalinks
permalink:      /:year-:month-:day/:title
paginate_path:  /blog/page:num/

# Setup
title:          "daydream" 
paginate:       5
baseurl:        ""
url:            "https://rvrie.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Joppe Geluykens
  url:          https://rvrie.com
  email:        joppe@rvrie.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
