# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          jppgks 
paginate:       5
baseurl:        ""
url:            "https://jppgks.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Joppe Geluykens
  url:          https://jppgks.github.io
  email:        joppe@youngwolves.co

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
